### ISSUE TITLE
Preprocessors removed for solving linker error

### ISSUE THREAD

**Issue by JangoBoogaloo** [hcilab-um/ArmFatigueCE#8]
Removed the following from OpenFrameworksCE => C++ => preprocessor Definition:

DEBUG;PROFILE;_WINDOWS;

may have potential problem for OpenFrameworks?

**Comment by jhincapie** [comment]
I think you should leave those flags in. Those are standard flags and for
sure OF has code conditional to them.

On Friday, February 21, 2014, JangoBoogaloo notifications@github.com
wrote:

> Removed the following from OpenFrameworksCE => C++ => preprocessor
> Definition:
> 
> DEBUG;PROFILE;_WINDOWS;
> 
> may have potential problem for OpenFrameworks?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/hcilab-um/ArmFatigueCE/issues/8
> .

## 

---

Juan David Hincapié Ramos, PhD
University of Manitoba - Canada

Address: University of Manitoba Winnipeg, Manitoba Canada  R3T 2N2
Office: E2-585
E-mail: jdhr@cs.umanitoba.ca

## W3: http://blog.jhincapie.com/
